/*
 * This source file was generated by the Gradle 'init' task
 */
package real_time_selenium_java_automation_testing_tasks;

import real_time_selenium_java_automation_testing_tasks.Interview_Task_1.printFoundersListAtWikipedia;

public class App {

    public static void Task_1_printFoundersList(){

        printFoundersListAtWikipedia task_1 = new printFoundersListAtWikipedia();

        task_1.printFoundersList();       
    }


    public static void main(String[] args) {

        Task_1_printFoundersList();       
    }
}
